### ISSUE TITLE
1.0.2 Update Causing Error

### ISSUE THREAD

**Issue by paulmist** [jameelmoses/acf-flexible-content-preview#5]
The latest update is throwing an error on pages (in WP Admin) using Custom Fields.

`Notice: Undefined index: ID in /wp-content/plugins/advanced-custom-fields-pro/includes/acf-field-functions.php on line 361`

Appears to be related to `acf_get_fields($layout_field)`.

**Comment by benvoynick** [comment]
I've committed 946bc90b7c3249f1be44b16aa043ebe1f5ebac8e to resolve this and related issues.

As @paulmist noted in #4 the nesting level for the subfield loop was not right, and so a lot of subfields were potentially getting missed.

The warning was caused because acf_get_fields() requires a WordPress post ID (which anything below the Field Group level does not have). Thankfully it is not necessary to call that function on the individual layouts: while acf_get_field_groups() does not populate field data, acf_get_fields() _does_ return recursive field group data.

I've refactored the code to split the recursive portion out into another method that calls itself, which I think makes things a little easier to read. It also means that even deeper nesting levels are supported. While going deeper probably wouldn't be a good user experience, the plugin will allow it for anyone who wants. :)

**Comment by jameelmoses** [comment]
Thanks, @benvoynick. @paulmist this is now resolved and released. Thanks for reporting!

**Comment by paulmist** [comment]
@benvoynick brilliant! Thank you for tidying up my mess.

Perhaps you can have a stab at Covid19 next?

I was looking for some good documentation on the ACF functions but struggled.

**Comment by jameelmoses** [comment]
@paulmist while you’re here, check out https://github.com/jameelmoses/acf-flexible-content-extended. It provides the same functionality for image previews of layouts with the added improved UX of editing layouts in a modal so your backend pages aren’t so long
